---
- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
    enabled: true

- name: Reload sysctl parameters
  ansible.builtin.command: sysctl --system
  changed_when: true
