---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: "rsyslog"
    state: restarted

- name: Restart chrony
  ansible.builtin.service:
    name: "chrony"
    state: restarted

- name: Restart snmpd
  ansible.builtin.service:
    name: "snmpd"
    state: restarted
