---
strongswan_packages:
  - strongswan
  - strongswan-starter
  - libcharon-extra-plugins
strongswan_connections: {}
strongswan_enabled: false
strongswan_manage_service: true
strongswan_ha_interface: "{{ keepalived_ha_interface | default('') }}"
strongswan_ha_virtual_ip: "{{ keepalived_virtual_ip | default('') }}"
